pipeline:
  name: Build express-hello-world
  identifier: Build_express_hello_world_1688203759370
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "Welcome to Harness CI"
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1688203707727
        repoName: 7054company/express-hello-world
        build: <+input>
